name: SimpleSelfProtect
main: gigabytedx.Main
version: 1.5
description: >
             Players can protect their stuff simply by placing a block.
commands:
  friend:
  unfriend:
  accept:
  hat:
depend: [WorldGuard, WorldEdit]